### ISSUE TITLE
Using Shapelets Just for Feature Extraction

### ISSUE THREAD

**Issue by smrtslckr** [mohaseeb/shaplets-python#1]
Great work on this library by the way!  I am writing to inquire about how I could best apply shapelet transformation to my use case.  If I simply wanted to get the transformed shaplets features on a multivariate time series (cross sectional/panel data), what would I do? What I think I would like to do is to do a shapelet transformation to generate features from a time series to then feed in a keras deep neural network for traditional binary classification.  Does this sound advisable to you or would you recommend a different approach?  Thanks again, John

**Comment by rsravan91** [comment]
Is the output of aggregation layer is what you are looking for ? If yes, then 
c  = classifier.fit(train_data, train_labels)
c.network.layers[0].current_output

**Comment by mohaseeb** [comment]
It depends on the specific data and problem, but before attempting to learn a shapelet based feature representation for my data and use that to train a neural network as suggested, I may try first training a CNN using the original data (to do the binary classification). The CNN  can simply handle the multivariate time-series inputs and has the capacity to learn features (through its filters and their hierarchy) relevant to the classification task.

As rsravan91 hinted, you need to train the classifier first (classifier.fit) to learn the shaplets. Note, the algorithm expects a univariate time series inputs, so you need to first somehow transform your multivariate time series inputs. 
After training, to extract feature vector for a given input, e.g. x, you would 
- call classifier.predict(np.array([x]))   (predict expects an input of shape (batch_size, input_size)). This will perform a forward pass over the graph.
- then get the Aggregation layer output. Each value in the output feature vector corresponds to the soft min distance between one of the shaplets and the input x. Note currently, you can't access the feature vector by calling classifier.network.layers[0].current_output; you need to "hack" something to get it; [see here](https://github.com/mohaseeb/shaplets-python/blob/7315f339117a4be8d633e758c8f74d05966b3309/shapelets_lts/classification/shapelet_models.py#L70).
