### ISSUE TITLE
availablity of  shapelet clustering

### ISSUE THREAD

**Issue by texaspandaa** [mohaseeb/shaplets-python#13]
hi there,

thanks for sharing the implementation, is it possible to provide the implementation of shapelet clustering in addition to classification?

best,

pandaa

**Comment by mohaseeb** [comment]
Hi Pandaa, 
The LTS algorithm implemented didn't address clustering timeseries, so either one tweaks the LTS algorithm to perform clustering (I don't have a simple suggestion now), or use some other method for that. Unfortunately, I don't have room to work on this now.
