### ISSUE TITLE
can be your code used for multivariate time series prediction ?

### ISSUE THREAD

**Issue by Sandy4321** [mohaseeb/shaplets-python#16]
great code thanks
only can you clarify if 
 can be your code used for multivariate time series prediction
like 
https://github.com/alan-turing-institute/sktime/blob/master/examples/multivariate_time_series_classification.ipynb

**Comment by Sandy4321** [comment]
can be your code used for multivariate time series classification 
for example  binary target : yes and not

**Comment by Sandy4321** [comment]
no answer?

**Comment by mohaseeb** [comment]
The LTS algorithm and this implementation don't support multidimensional input.
