### ISSUE TITLE
how to install shapelets package

### ISSUE THREAD

**Issue by vinaykrishna06** [mohaseeb/shaplets-python#2]
Hi,

Its seems there is yet another package names shapelets if we install through pip. 
So how we use this shapelets?

**Comment by rdhara** [comment]
Don't use the one from `pip`. Just clone the repo, change the directory to `shapelets-python/` , and refer to the example code provided.

**Comment by mohaseeb** [comment]
https://github.com/mohaseeb/shaplets-python#installation
