### ISSUE TITLE
where is the GunPower dataset？

### ISSUE THREAD

**Issue by khronosplus** [mohaseeb/shaplets-python#3]
when I ran the example.py，I found there have no GunPower dataset.

**Comment by mohaseeb** [comment]
Hi, I added some information in example.py on how you can download the GunPower dataset.

**Comment by khronosplus** [comment]
I used the Gun-Point dataset for training. But  I don't know how to save the best shapelets, could you help me. Recently, I am processing sensors data and I want to extract the best shapelet  of each class.

**Comment by mohaseeb** [comment]
I assume by best shaplets you meant the shapelets learnt by the LTS algorithm. You can get those as follows:
```python
clf = LtsShapeletClassifier(...)
clf.fit(train_data, train_labels)
aggregation_layer = clf.network.layers[0]
shaplets = [soft_min_layer.S.ravel() for soft_min_layer in aggregation_layer.layers]
```
