### ISSUE TITLE
Doesn't start the epoch 0

### ISSUE THREAD

**Issue by tharunShiv** [mohaseeb/shaplets-python#8]
When I use huge dataset(3000 rows, 80 columns) the program doesn't start the epoch 0 also, what is the reason? Any fix?

**Comment by mohaseeb** [comment]
Hi @tharunShiv 
Did it crash or log some errors? I tried the example in example.py using a dataset of 3000 rows & 150 columns and it worked. It was slow (as expected); ~15 min/epoch on a quad core i7 machine.

**Comment by tharunShiv** [comment]
Thank you so much for your kind reply, whoa I didn't wait for 15 mins. Will try that. By the way, great project!
